pipeline {
    agent any
/*agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }*/
    tools {
        maven 'maven 3.8.6'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('docker'){
            steps {
                sh 'docker build -t image .'
                sh 'docker run -d --name c${BUILD_NUMBER} -p 8081:80 image'
            }
        }
    }
}
